"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['cli.py']
DATA_FILES = []
OPTIONS = { 
    'argv_emulation': False,
    'packages': [
        'numpy',
        'mpld3',
        'matplotlib',
        'flask',
        'scipy',
        'flask_cors',
        'server',
        'server.api',
        'server.models'
    ]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
